### ISSUE TITLE
bug with a w/out href results

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#17]
* [test page](https://hanshillen.github.io/aria-test-builder/dist/testcases/anohref-test.html)
* using arc toolkit => send dom to ARIA checker
* returns only partial results
```
Summary
Details
Invalid roles
Back to the top
Element a has invalid role gridcell.

<a role="gridcell" class="role-test gridcell-test anohref-test" id="anohref-gridcell-2-test" aria-label="acc name" tabindex="0"></a>
Missing required state
Back to the top
Role checkbox missing required state (aria-checked).

<a role="checkbox" class="role-test checkbox-test anohref-test" id="anohref-checkbox-1-test" aria-label="acc name" tabindex="0"></a>
```

Expect full summary / that Any role is allowed on a w/out href

**Comment by gezlemon** [comment]
Fixed an uncaught exception error that was causing this issue.

**Comment by scottaohara** [comment]
seems there's still an issue with this one. bookmarklet returns same results for a with href.  
a without href should allow for any role

**Comment by gezlemon** [comment]
Fixed logic for anchor without an href

**Comment by scottaohara** [comment]
confirmed fixed
